### ISSUE TITLE
Mulit agent

### ISSUE THREAD

**Issue by jiafei1224** [TheMTank/ai2thor-experiments#11]
Hi, does the ai2thor_env allow mulit agent to run in the same room?

**Comment by beduffy** [comment]
Sorry, we haven't implemented a multi-agent functionality into our wrapper. However, the AI2Thor underneath in version 1.0 added this functionality and more can be found about this here:

https://github.com/allenai/ai2thor/blob/master/doc/static/ReleaseNotes/ReleaseNotes_1.0.md

If you would like to add a PR to this repo adding this functionality feel free to. Ask questions and reopen if you need help.

**Comment by jiafei1224** [comment]
Thank you, can i also check with you which part of the code in ai2thor_env.py controls the random selection of the ALL_possible action, i cant seen to find it.

**Comment by fernandotorch** [comment]
We followed the design principles recommended in gym documentation, which means that the environment contains the attribute `self.action_space`, from which you can sample a random action by using `self.action_space.sample()`.

You can find an example of this in our [random walk example](https://github.com/TheMTank/cups-rl/blob/master/examples/random_walk.py)

Also find more information about gym.spaces class and the sampling details in [gym documentation](http://gym.openai.com/docs/#spaces) or in their [github repository](https://github.com/openai/gym/tree/master/gym/spaces).

**Comment by jiafei1224** [comment]
Thank you. But if for Multi-Agent initialization, which part of the ai2thor_env.py will you advice me to put at?

**Comment by beduffy** [comment]
I assume implementing the multi-agent system within our wrapper would be quite complex. It might be better to first experiment with it in the ai2thor environment. Once you're comfortable with it there you might have a much clearer idea on how to implement it into our wrapper. 
I assume it will be complex because for each agent we will need to provide an action to the environment at each step. Once we see how this is done in the original underlying ai2thor we can see how to extend it to our wrapper if you would like to do so.

**Comment by zyzhang1130** [comment]
May I add on, will the complexity be reduced if the training of multi-agents only takes turns alternatively (for example, in a 2 agent setting, episode1 train agent1, episode2 train agent2, episode3 train agent1, episode4 train agent2 so on and so forth)

**Comment by beduffy** [comment]
@zyzhang1130 I think your example implies that there would be only 1 agent running in the environment at any instant and therefore wouldn't be strictly multi-agent but multiple agents training separately in the same environment. In general, multi-agent RL agents share the episode so that when the episode ends it ends for all the agents. In theory it's possible to have an episode tied to an agent's lifetime but this is rarer and harder to achieve since resetting the environment's objects would reset objects in other agent's episodes.

But in general this repo isn't capable of multi-agent at the moment and we don't have much experience with that field.

Check this blog for more info: https://rise.cs.berkeley.edu/blog/scaling-multi-agent-rl-with-rllib/

**Comment by zyzhang1130** [comment]
noted. one question not related to multi-agent but to your reply: so the environment will automatically reset after a new episode starts?

**Comment by beduffy** [comment]
In general, RL environments on a call to `env.reset()` the episode/environment resets. It's up to the environment designer to decide what happens in this function but it generally means that everything goes back to the initial position. 

My point above is that in multi-agent environments this can be different.

**Comment by zyzhang1130** [comment]
I see. Thank you!
