### ISSUE TITLE
How to add in new movement like Crouch and stand

### ISSUE THREAD

**Issue by jiafei1224** [TheMTank/ai2thor-experiments#12]
Hi,can advice me on how to add in new movement such as crouch and stand.
Thank you

**Comment by beduffy** [comment]
You can change the height of the camera with cameraY parameter in our wrapper but if you follow the code you'll see we use this in the initialize call in the reset function:
https://github.com/TheMTank/cups-rl/blob/master/gym_ai2thor/envs/ai2thor_env.py#L253

To be able to change this within the step function (e.g. an action to crouch and set cameraY lower and similar for standing), you'll need to do a bit of experimentation. A few ideas:
- initialise on every crouch/stand command and store saved agent and object locations to set them all to the right place as before the initalize. Probably a VERY BAD idea.
- Change the C# Unity code within ai2thor so that you can set the cameraY within the episode and without calling initialize. For example you could add a setter function for camera height to change this without calling initializing. It might be only 3 lines of code but you'll have to experiment and read the Unity code yourself to find out. 

It's also possible to try out another 3D environment e.g. ViZDoom, House3d, or anything else mentioned here: https://github.com/TheMTank/RL-code-resources

If you have any questions feel free to ask.

**Comment by jiafei1224** [comment]
Hi there, i try to add in the concept of a multi-agent, but there isnt an attribute of frame for the mulit-agent function yet.  Is there anyway i can go by it?
