### ISSUE TITLE
ploting the result

### ISSUE THREAD

**Issue by zyzhang1130** [TheMTank/ai2thor-experiments#17]
Hi,
I have another question. After I run the main.py of rainbow there is no plot coming out, but clearly in the test.py there is a  _plot_line command which is supposed to be called if the main.py is executed. After checking, it is discovered that in main.py line149:
avg_reward, avg_Q = test(env, mem_steps, args, dqn, val_mem, evaluate_only=True)
and line179:
 if num_steps % args.evaluation_interval == 0: 
(hence line182  avg_reward, avg_Q = test(env, num_steps, args, dqn, val_mem) ) 

were never executed, which means that:
if args.evaluate_only:           #line147
and
 if num_steps >= args.learn_start:          #line172

were never satisfied.

I didn't modify any part of the code except changing --max-num-steps (line 34) to 1000 for checking result promptly.

Do you have any clue what is the cause?

Thank you.

**Comment by beduffy** [comment]
`'--evaluation-interval', type=int, default=1e5`
evaluation-interval is 1e5 which is 100,000, you probably just didn't wait this long. You should set that argument number lower (e.g. 2000) and then you will execute test sooner due to line 179 and then this will plot the results and save the model if the average reward is best.

**Comment by zyzhang1130** [comment]
Hi, it worked. Thank you for the advice!
